apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-production
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: kubeapp  
  template:
    metadata:
      name: kubeapp
      labels:
        app: kubeapp
        env: production 
    spec:
      containers:
      - name: kubeapp
        image: canary-app:1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        command: ["/app"]
        ports:
        - name: kubeapp
          containerPort: 8080
