apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-production
spec: 
  replicas: 3
  selector:
    matchLabels:
<<<<<<< HEAD
      app: kubeapp  
=======
      app: hello-world  
>>>>>>> 8e2d1377b9d0dbb648cc61e182c22600dca44126
  template:
    metadata:
      name: kubeapp
      labels:
        app: kubeapp
        env: production 
    spec:
      containers:
      - name: kubeapp
        image: PROJECT_ID-app:1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        command: ["/app"]
        ports:
        - name: kubeapp
          containerPort: 8080
